# Generated by Django 3.2.7 on 2021-09-26 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('loc_state', models.CharField(max_length=254)),
                ('loc_city', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('phone', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=254)),
                ('l_name', models.CharField(max_length=254)),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(max_length=1)),
                ('dob', models.DateField(null=True)),
                ('in_date', models.DateField(auto_now_add=True, null=True)),
                ('h_origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register.hospital')),
                ('t_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register.tutor')),
            ],
        ),
    ]
