# Generated by Django 3.2.7 on 2021-09-27 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='loc_city',
        ),
    ]
